### ISSUE TITLE
Add delimiter in order to parse grep results

### ISSUE THREAD

**Issue by petobens** [coreyja/devicon-lookup#7]
Is is possible to add a "delimiter" flag in order to signal the end of the filename? My use is that I want to add devicons to rg grep results however the current parsing always default to the default icon:
![image](https://user-images.githubusercontent.com/2583971/54496831-6ec13a80-48d2-11e9-8f30-ed6129fc084a.png)

**Comment by coreyja** [comment]
Hello again @petobens!

Ahh this is an interesting use case, I definitely think we should support something like this.

I wonder if a delimiter flag is the best solution for the problem though. My initial thought is that maybe we could supply an option to specify a regex that is used to find the path in the line. I feel like that might cover a wider range of different use cases!

**Comment by petobens** [comment]
Yep, that sound a bit more general. Thanks!

**Comment by coreyja** [comment]
This got closed cause I merged the PR with this feature in it :tada:

But I'm gonna re-open it until i get a release cut! Which I will do in the next few days just want to get some docs and stuff in line!

**Comment by coreyja** [comment]
This was released as part of `0.8.0` 🎉 

Thanks again @petobens for bring up the issue!

**Comment by petobens** [comment]
Hey @coreyja thanks for implementing this. I tried it out and have one question. 
As it can be seen in the image below if I run:
```
rg --vimgrep --type python --color=always f | devicon-lookup --color --prefix : | fzf --ansi --delimiter=: --preview 'bat --color always {1}'
```
I cannot get `bat` to preview the file since it tries to open `' python/onedarkish.py'` instead of just `python/onedarkish.py`. Do you happen to know how can I strip the leading icon?

![image](https://user-images.githubusercontent.com/2583971/78262669-4c975c00-74d7-11ea-85e4-0d80a859c6c8.png)

**Comment by coreyja** [comment]
@petobens  Yup I do! Basically it throws a quick little `sed` into the preview command so that we can strip the icon before passing it to `bat`

This idea (and `sed` snippet[1]) came from the `vim` integration plugin over at `fzf.devicon.vim` [2] if you are interested!

```
rg --vimgrep --color=always f | devicon-lookup --color --prefix : | fzf --ansi --delimiter=: --preview 'bat --color always $(echo {1} | sed "s/[^ ] //")'
```

[1] (https://github.com/coreyja/fzf.devicon.vim/blob/master/bin/preview.sh#L13)
[2] (https://github.com/coreyja/fzf.devicon.vim)

**Comment by petobens** [comment]
Thanks for the quick reply. I'm trying to use your trick from a script but cannot make it work:
```bash
FZF_GREP_OPTS="
--ansi
--delimiter=:
--preview 'bat --color always --line-range {2}: --highlight-line {2} $(echo {1} | sed "s/[^ ] //")'
"
cmd="rg --smart-case --vimgrep --color=always foo | devicon-lookup --color --prefix :"
eval "$cmd" | FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $FZF_GREP_OPTS"  fzf
```
Say the script is named `bar.sh` and when I run `bash bar.sh` I get:

![image](https://user-images.githubusercontent.com/2583971/78267716-a4d15c80-74dd-11ea-8789-954e1792d078.png)

Any pointers? Thanks in advance

**Comment by petobens** [comment]
Forget about that.  I figured it out... It wasn't expanding/executing the grep default opts variable
